### ISSUE TITLE
Use case: Fully dressed description

### ISSUE THREAD

**Issue by nymann** [creditoro/report#19]
https://overleaf.nymann.dev/project/5e7c977f6b7ee20075efc0a1

- [x] B03 - Opret bruger
- [x] B04 - Opret person
- [x] B07 - Opret krediteringer
- [x] B10 - Læs krediteringer
- [x] B13 - Log ind
- [x] B15 - Log af
- [x] B15 - Se personinformationer
- [x] B16 - Godkend nye krediteringer

**Comment by nymann** [comment]
Starting on log in.

**Comment by mara816** [comment]
Create user (Opret bruger)

**Comment by Bokaiii** [comment]
Godkend nye krediteringer c:

**Comment by Joergenson** [comment]
<details>
  <summary>Hvad kan det være?</summary>
Se personinformationer :P
</details>

**Comment by Bokaiii** [comment]
Opret Person
