### ISSUE TITLE
Resume

### ISSUE THREAD

**Issue by Kechr** [creditoro/report#41]
- En kort introduktion til projektet - hvad blev der arbejdet med og hvorfor.
- Problemformuleringen og vigtige afgrænsninger
- Metode - hvordan angreb I problemet og hvordan realiserede I løsningen (hvem, hvad, hvornår og hvorfor)
- Hovedresultater og konklusioner – hvad kom der ud af arbejdet.

(max 1 side)

**Comment by Kechr** [comment]
- En kort introduktion til projektet - hvad blev der arbejdet med og hvorfor.
- Problemformuleringen og vigtige afgrænsninger
- Metode - hvordan angreb I problemet og hvordan realiserede I løsningen (hvem, hvad, hvornår og hvorfor)
- Hovedresultater og konklusioner  – hvad kom der ud af arbejdet.

(max  1 side)

**Comment by Bokaiii** [comment]
Mangler:
- Indsæt konklusion
